name = "StartUpDG"
uuid = "472ebc20-7c99-4d4b-9470-8fde4e9faa0f"
authors = ["Jesse Chan", "Yimin Lin"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
